# Generated by Django 5.2.1 on 2026-05-06 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS_DENIED', 'Acceso denegado'), ('VALIDATION', 'Validación'), ('ERROR', 'Error')], max_length=30)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('app_label_field', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('object_pk', models.CharField(blank=True, max_length=80)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_audite_created_9a257b_idx'), models.Index(fields=['action'], name='core_audite_action_9297cd_idx'), models.Index(fields=['level'], name='core_audite_level_057b82_idx'), models.Index(fields=['user'], name='core_audite_user_id_907bed_idx'), models.Index(fields=['app_label_field', 'model_name'], name='core_audite_app_lab_8ae16c_idx')],
            },
        ),
    ]
