# Generated by Django 5.2.1 on 2026-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Paciente'), ('STAFF', 'Personal')], default='STAFF', max_length=20),
        ),
    ]
