# Generated by Django 5.2.1 on 2026-05-06 00:11

import apps.doctors.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialtyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senescyt_pdf', models.FileField(upload_to=apps.doctors.models.doctor_senescyt_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('registration_code', models.CharField(blank=True, help_text='Código o número de registro SENESCYT, si aplica.', max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_credentials', to='doctors.doctor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_doctor_specialty_credentials', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_credentials', to='specialties.specialty')),
            ],
            options={
                'verbose_name': 'Credencial SENESCYT por especialidad',
                'verbose_name_plural': 'Credenciales SENESCYT por especialidad',
                'ordering': ['doctor__user__last_name', 'specialty__name'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'specialty'), name='uq_doctor_specialty_credential')],
            },
        ),
    ]
